### ISSUE TITLE
Question: What is the correct baud rate to monitor the log messages

### ISSUE THREAD

**Issue by moizhraj** [maxgerhardt/pio-azure-iot-arduino-demo#1]
Hey Max, Thanks for adding this sample. I was trying it and it worked fine for me however when i try to run serial monitor I see garbled values and not able to identify whats the correct baud rate in use here. ( tried 9600 and 115200. Any ideas? Thanks again.

**Comment by maxgerhardt** [comment]
In `main.cpp` the example does

https://github.com/maxgerhardt/pio-azure-iot-arduino-demo/blob/7eb35681c6c20a74d90d2788d651b931e67f6db9/src/main.cpp#L210

which does

https://github.com/maxgerhardt/pio-azure-iot-arduino-demo/blob/7eb35681c6c20a74d90d2788d651b931e67f6db9/src/sample_init.h#L11-L14

which maps to the Azure IoT utility library and this function: 

https://github.com/Azure/azure-iot-arduino-utility/blob/cd716a66dd69036ba65a6189a05989a2e0f19dfa/src/esp32/sample_init.cpp#L17-L21

which reads as

```cpp

static void initSerial() {
    // Start serial and initialize stdout
    Serial.begin(1000000);
    Serial.setDebugOutput(true);
}
```

so the baud rate is 1 Megabaud or 1000000 baud. 

I've fixed the default `monitor_speed` in the `platformio.ini` to automatically choose the correct baud rate now in https://github.com/maxgerhardt/pio-azure-iot-arduino-demo/commit/88e065f33935a908a9ab3ebb22e5bc11537c3364.
