### ISSUE TITLE
SSL handshake issue

### ISSUE THREAD

**Issue by moizhraj** [maxgerhardt/pio-azure-iot-arduino-demo#2]
Hi Max, I am getting one error in establishing a connection to IoT Hub. It says "Failure SSL handshake -9984" followed by "failure opening connection to endpoint" and "The device client has been disconnected". Are you having similar issues? I just want to confirm if that is the case then ill raise an issue on the SDK repo.

Apart from your code, I have added certs.h and certs.c that are there on the SDK but still see this issue. Any thoughts? 

Thanks

**Comment by maxgerhardt** [comment]
>Failure SSL handshake -9984

That comes from mbedtls. 9984 decimal is 0x2700 and has [the meaning](https://github.com/ARMmbed/mbedtls/blob/e8582ba0f3858d59ad7321ae56c95e2f4e05e657/include/mbedtls/x509.h#L72)

```
#define MBEDTLS_ERR_X509_CERT_VERIFY_FAILED               -0x2700  /**< Certificate verification failed, e.g. CRL, CA or signature check failed. */
```

So somewhere a certificate check has failed. Are you sure you've selected the right `USE_X_CERT` flag from

https://github.com/Azure/azure-iot-arduino/blob/3306566893a886a44885399d6ce9296a72271ccd/src/certs/certs.c#L14-L16

regarding the server you're connecting to?

I'll try and run this firmware myself and see what errors I'm running into.

**Comment by moizhraj** [comment]
Thanks, and yes, tried all the available certs but still the same.

**Comment by maxgerhardt** [comment]
Hmm unfortunately I'm not able to create a Azure account for students because there's an activation error. The way I see it one has to create an IoT-Hub and then add a device to it [as documented](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-create-through-portal). Then one has to get the device connection string for it and put it into the `iot_configs.h` file.

I think the connecting server then depends on the location of the device; This example features the general cert, a chinese and a german one. Maybe yours is just missing. 

Can you please increase the debug level in Arduino to maximum by adding `-DCORE_DEBUG_LEVEL=5` to the `build_flags = ..` line ([docs](https://docs.platformio.org/en/latest/platforms/espressif32.html#debug-level)) of the `platformio.ini` and upload the complete serial log either here to to pastebin.com if it's too big? Make sure to remove sensitive information like the device connection string or credentials though. 

If the logs show the server that is being connected to it I can check what certificate it's using and add it if necessary.

**Comment by maxgerhardt** [comment]
Wait, actually there's an easier way to find this out. As I'm reading the code, the host name to connect to is parsed from the connection string, which is separated by semicolons and value assigned by equal signs. What does your connection string say after `HostName`?

**Comment by moizhraj** [comment]
> What does your connection string say after `HostName`?

its `xxxx.azure-devices.net`

and my full connection string is  `HostName=xxxx.azure-devices.net;DeviceId=esp32;SharedAccessKey=xxxx`

Also, the verbose level of debugging doesn't output any extra details :(

**Comment by maxgerhardt** [comment]
Okay I though `xxxx.azure-devices.net` was a censored name but this thing actually exists.. doing a `openssl s_client -showcerts -host xxxx.azure-devices.net -port 443` gives me the certificate chain

``` 
---
Certificate chain
 0 s:/CN=*.azure-devices.net
   i:/C=US/O=Microsoft Corporation/CN=Microsoft RSA TLS CA 01
-----BEGIN CERTIFICATE-----
MIIH0jCCBbqgAwIBAgITawAB8FwcyIroj0WnzgAAAAHwXDANBgkqhkiG9w0BAQsF
ADBPMQswCQYDVQQGEwJVUzEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
MSAwHgYDVQQDExdNaWNyb3NvZnQgUlNBIFRMUyBDQSAwMTAeFw0yMDEwMjkyMjAy
MzRaFw0yMTEwMjkyMjAyMzRaMB4xHDAaBgNVBAMMEyouYXp1cmUtZGV2aWNlcy5u
ZXQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCtbapRrAPArURJsnmW
u4tr5MsEHTspLqBdd/6emyE8F2Vi3RXkhhxKT77XsVZJYKOryNOxNo1ICilmrO/U
snSFYHqSrLyebjpLSaZH8Nt8B/4u8m6yurh/zPDBBlnhiLNZ9WzwlfaIayW9IkyI
mVwB/g6ThdAfvf6hSs465Vhh9mjf5oZCdolvfbotAqv1o1cCdYEgLu2g1PiGFm7L
bdcqsOleIYjR36X5NgLQ4J5ZZK9MOh53zjFC3EbaR982MYMU4SOtWkv+XX2HRojI
dgzskeaNEMa0tD7FHB9MXQbxlhQnQZxxS689HccBAqlWxTmZUH0YA0pTxTMBFeFj
O6PJAgMBAAGjggPWMIID0jCCAQQGCisGAQQB1nkCBAIEgfUEgfIA8AB2APZclC/R
dzAiFFQYCDCUVo7jTRMZM7/fDC8gC8xO8WTjAAABdXZrhDoAAAQDAEcwRQIhANb4
DiWOK1kXKU5nRoGxGYm4o2EIo5WiNvUMjx3bnhudAiBoP0lqLCPq6qAA1HV3bY9i
rjh7kt5RCo5vyfkE07G8gAB2AFWB1MIWkDYBSuoLm1c8U/DA5Dh4cCUIFy+jqh0H
E9MMAAABdXZrhf0AAAQDAEcwRQIhAKymLgnWbi38vGImaXx1i/Y7c+BkpPkpT0xH
kI0kkNHEAiBrwfjjNGtr8wDDaf19phsy1+dZ99z3Ern/+23s0225dDAnBgkrBgEE
AYI3FQoEGjAYMAoGCCsGAQUFBwMBMAoGCCsGAQUFBwMCMD4GCSsGAQQBgjcVBwQx
MC8GJysGAQQBgjcVCIfahnWD7tkBgsmFG4G1nmGF9OtggV2Fho5Bh8KYUAIBZAIB
JTCBhwYIKwYBBQUHAQEEezB5MFMGCCsGAQUFBzAChkdodHRwOi8vd3d3Lm1pY3Jv
c29mdC5jb20vcGtpL21zY29ycC9NaWNyb3NvZnQlMjBSU0ElMjBUTFMlMjBDQSUy
MDAxLmNydDAiBggrBgEFBQcwAYYWaHR0cDovL29jc3AubXNvY3NwLmNvbTAdBgNV
HQ4EFgQUNxH2GXP7Za4puUCdkJ5/NwJIdKkwCwYDVR0PBAQDAgSwMF0GA1UdEQRW
MFSCEyouYXp1cmUtZGV2aWNlcy5uZXSCGiouYW1xcHdzLmF6dXJlLWRldmljZXMu
bmV0giEqLnN1Lm1hbmFnZW1lbnQtYXp1cmUtZGV2aWNlcy5uZXQwgbAGA1UdHwSB
qDCBpTCBoqCBn6CBnIZNaHR0cDovL21zY3JsLm1pY3Jvc29mdC5jb20vcGtpL21z
Y29ycC9jcmwvTWljcm9zb2Z0JTIwUlNBJTIwVExTJTIwQ0ElMjAwMS5jcmyGS2h0
dHA6Ly9jcmwubWljcm9zb2Z0LmNvbS9wa2kvbXNjb3JwL2NybC9NaWNyb3NvZnQl
MjBSU0ElMjBUTFMlMjBDQSUyMDAxLmNybDBXBgNVHSAEUDBOMEIGCSsGAQQBgjcq
ATA1MDMGCCsGAQUFBwIBFidodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpL21z
Y29ycC9jcHMwCAYGZ4EMAQIBMB8GA1UdIwQYMBaAFLV2DDARzseSQk1Mx1wsyKkM
6AtkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjANBgkqhkiG9w0BAQsF
AAOCAgEAbtB471zHvIyALjg0lLm68ESx2G/mR6GY35L1MnSu7N8Tzgw90ysZlYTq
rXpffQiFyhNM/TC5MrSFUby5t4VjEuxmuLcswIjWw4llkVDjLkMKEqeALztT3cVa
otjLHR8KJPOjKd7/TppRonKe70QSCif05Y2o+zI9XCJkbEsT4Gq7sbroCxMpb8gw
NgKgs3/HPGkQXWKm2ns67xm0KjyxITVuvo3XeZwETW7wmvWxBUDdZ5vmv/OwHAvP
Zd1ldBsofdUfR5PU7h7/8+lybisen6KZaIFPFOZIsFUeJwqaOAqLa2wyXdThXZR1
OIDp/pLhgjspVebdH/6wzdIJEpfjbuA+EssAjaiACFeLta+qImbfqrq4jIixgptz
DmpnaO1JGT5pkyu+FbFiwTm+s6xWDxxiQkjnY5moGxYqyd1ItSi7oNYiVDS1rudC
FruoYgaP9DSTHHwyzl7z6onUtU9yF387fMCupnvYkEjLm86NgU3FyJ5l9+KCOXtX
ZpjS81KcxBoHwqsNvnwGYla5TA9xPrrVFCeW9CEe/8wj68W7voB8ILJg5JSBK185
Kr2AXzll25qwa7M5YsC91zEzlgaIfcMWGZn/WbmFV29NmxXdbXCkG1s6s1wu6ySs
AcMVvyK3EXFPrMwIsK8vwiKKaCYBU8hyMdY5atwsJYrMb5UDuqg=
-----END CERTIFICATE-----
 1 s:/C=US/O=Microsoft Corporation/CN=Microsoft RSA TLS CA 01
   i:/C=IE/O=Baltimore/OU=CyberTrust/CN=Baltimore CyberTrust Root
-----BEGIN CERTIFICATE-----
MIIFWjCCBEKgAwIBAgIQDxSWXyAgaZlP1ceseIlB4jANBgkqhkiG9w0BAQsFADBa
MQswCQYDVQQGEwJJRTESMBAGA1UEChMJQmFsdGltb3JlMRMwEQYDVQQLEwpDeWJl
clRydXN0MSIwIAYDVQQDExlCYWx0aW1vcmUgQ3liZXJUcnVzdCBSb290MB4XDTIw
MDcyMTIzMDAwMFoXDTI0MTAwODA3MDAwMFowTzELMAkGA1UEBhMCVVMxHjAcBgNV
BAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEgMB4GA1UEAxMXTWljcm9zb2Z0IFJT
QSBUTFMgQ0EgMDEwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCqYnfP
mmOyBoTzkDb0mfMUUavqlQo7Rgb9EUEf/lsGWMk4bgj8T0RIzTqk970eouKVuL5R
IMW/snBjXXgMQ8ApzWRJCZbar879BV8rKpHoAW4uGJssnNABf2n17j9TiFy6BWy+
IhVnFILyLNK+W2M3zK9gheiWa2uACKhuvgCca5Vw/OQYErEdG7LBEzFnMzTmJcli
W1iCdXby/vI/OxbfqkKD4zJtm45DJvC9Dh+hpzqvLMiK5uo/+aXSJY+SqhoIEpz+
rErHw+uAlKuHFtEjSeeku8eR3+Z5ND9BSqc6JtLqb0bjOHPm5dSRrgt4nnil75bj
c9j3lWXpBb9PXP9Sp/nPCK+nTQmZwHGjUnqlO9ebAVQD47ZisFonnDAmjrZNVqEX
F3p7laEHrFMxttYuD81BdOzxAbL9Rb/8MeFGQjE2Qx65qgVfhH+RsYuuD9dUw/3w
ZAhq05yO6nk07AM9c+AbNtRoEcdZcLCHfMDcbkXKNs5DJncCqXAN6LhXVERCw/us
G2MmCMLSIx9/kwt8bwhUmitOXc6fpT7SmFvRAtvxg84wUkg4Y/Gx++0j0z6StSeN
0EJz150jaHG6WV4HUqaWTb98Tm90IgXAU4AW2GBOlzFPiU5IY9jt+eXC2Q6yC/Zp
TL1LAcnL3Qa/OgLrHN0wiw1KFGD51WRPQ0Sh7QIDAQABo4IBJTCCASEwHQYDVR0O
BBYEFLV2DDARzseSQk1Mx1wsyKkM6AtkMB8GA1UdIwQYMBaAFOWdWTCCR1jMrPoI
VDaGezq1BE3wMA4GA1UdDwEB/wQEAwIBhjAdBgNVHSUEFjAUBggrBgEFBQcDAQYI
KwYBBQUHAwIwEgYDVR0TAQH/BAgwBgEB/wIBADA0BggrBgEFBQcBAQQoMCYwJAYI
KwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTA6BgNVHR8EMzAxMC+g
LaArhilodHRwOi8vY3JsMy5kaWdpY2VydC5jb20vT21uaXJvb3QyMDI1LmNybDAq
BgNVHSAEIzAhMAgGBmeBDAECATAIBgZngQwBAgIwCwYJKwYBBAGCNyoBMA0GCSqG
SIb3DQEBCwUAA4IBAQCfK76SZ1vae4qt6P+dTQUO7bYNFUHR5hXcA2D59CJWnEj5
na7aKzyowKvQupW4yMH9fGNxtsh6iJswRqOOfZYC4/giBO/gNsBvwr8uDW7t1nYo
DYGHPpvnpxCM2mYfQFHq576/TmeYu1RZY29C4w8xYBlkAA8mDJfRhMCmehk7cN5F
JtyWRj2cZj/hOoI45TYDBChXpOlLZKIYiG1giY16vhCRi6zmPzEwv+tk156N6cGS
Vm44jTQ/rs1sa0JSYjzUaYngoFdZC4OfxnIkQvUIA4TOFmPzNPEFdjcZsgbeEz4T
cGHTBPK4R28F44qIMCtHRV55VMX53ev6P3hRddJb
-----END CERTIFICATE-----
---
Server certificate
subject=/CN=*.azure-devices.net
issuer=/C=US/O=Microsoft Corporation/CN=Microsoft RSA TLS CA 01
---
```
I'll add these to the certificates and then you can try that.

**Comment by maxgerhardt** [comment]
Please retry with the following `platformio.ini`

```
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    AzureIoTHub=https://github.com/maxgerhardt/azure-iot-arduino.git
    AzureIoTUtility
    AzureIoTProtocol_MQTT
    AzureIoTProtocol_HTTP
    AzureIoTSocket_WiFi ; will be taken from lib/
build_flags = -DDONT_USE_UPLOADTOBLOB -DUSE_BALTIMORE_CERT -DUSE_MBEDTLS
; set in AzureIoTUtility/src/esp32/sample_init.cpp:initSerial 
monitor_speed = 1000000
```

It will use my fork with the updated certificates ([there](https://github.com/maxgerhardt/azure-iot-arduino/blob/2a1c919a13bb7e85cf2f26ec1792fec70e3c5b65/src/certs/certs.c#L19-L22))

**Comment by maxgerhardt** [comment]
If this doesn't work, most likely your connection string is wrong. The "xxxx" in it seems to me like Azure hasn't given you the full uncensored connection string or you've setup your device incorrectly.

**Comment by moizhraj** [comment]
> Okay I though `xxxx.azure-devices.net` was a censored name

I **did** censor the hostname but I believe that hostname exists and that's why it gave you those certs, using s_client

![image](https://user-images.githubusercontent.com/44790182/99891349-de4a0a00-2c1d-11eb-8de2-3a447e470515.png)

Can you share more details of this s_client on how to use it, ill try with my hub name?

**Comment by maxgerhardt** [comment]
s_client is part of the openssl binary. Just execute the command on Linux or download the windows binaries and execute them on the command line.

**Comment by moizhraj** [comment]
> s_client is part of the openssl binary. Just execute the command on Linux or download the windows binaries and execute them on the command line

Thanks, Fetched the correct certs using `s_client`, and now m getting a different error code - `Failure ssl handshake -10368`

**Comment by maxgerhardt** [comment]
>Failure ssl handshake -10368

Thats `-0x2880` and [means](https://github.com/ARMmbed/mbedtls/blob/e8582ba0f3858d59ad7321ae56c95e2f4e05e657/include/mbedtls/x509.h#L75)

```cpp
#define MBEDTLS_ERR_X509_ALLOC_FAILED                     -0x2880  /**< Allocation of memory failed. */
```

so you're running out of memory during the handshake or some certificate allocation.., for an ESP32 that's quite a feat with its 320kByte free data RAM. 

Have you made sure you only store the root certificate (first in chain) in the `certs.c` and there are **no other certs** in there? You can just hardcode that one cert while removing all others for a test. 

Of course a TLS handshake will need a variable amount of memory that is dependent on the used certificates and ciphersuites. A handshake where you have to verify three RSA-2048 certs will take an extreme amount of memory compared to one with ECDSA and a curve like NIST-P256. Using efficient certificates depends on the server though, you can't change that (except change the server).. Since I don't know which certificate chain / host you're connecting to, I don't have more details.

If your ESP32 board has a PSRAM chip (e.g. 4MB on the `ESP32-WROVER` module) it's also possible to activate that so that it gives you more allocatable RAM. Do you have such a module?

However, considering that this example also exists for an ESP8266 with like 80kByte of RAM, something is fishy here if it can also be run on that ESP8266.

**Comment by moizhraj** [comment]
> If your ESP32 board has a PSRAM chip (e.g. 4MB on the `ESP32-WROVER` module)

No, I don't think I have that. I am using [this](https://www.amazon.com/HiLetgo-ESP-WROOM-32-Development-Microcontroller-Integrated/dp/B0718T232Z) one, but as you mentioned, it supports ESP8266, I guess it's using the embedded C SDK. I haven't tried with embedded C SDK so maybe will have to give it a shot, not sure if there is any library support on platformio.

> Have you made sure you only store the root certificate (first in chain) in the `certs.c` and there are **no other certs** in there? You can just hardcode that one cert while removing all others for a test.

so when I use below two certs I got from OpenSSL based on my hostname and nothing from the sample, it gives me a `0x2700 - Certificate verification failed, e.g. CRL, CA or signature check failed.` 

And when I use these two along with the Baltimore cert from the samples its - `unable to mallocAndStrcpy_s TrustedCerts value`

Certs from OpenSSL:
`
const char certificates[] = 
/* certs from xxxx.azure-devices.net  */
"-----BEGIN CERTIFICATE-----\r\n"
"MIIH0DCCBbigAwIBAgITfwACt67vKh58hD6ycAAAAAK3rjANBgkqhkiG9w0BAQsF\r\n"
"ADBPMQswCQYDVQQGEwJVUzEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9u\r\n"
"MSAwHgYDVQQDExdNaWNyb3NvZnQgUlNBIFRMUyBDQSAwMjAeFw0yMDExMTMxNzA3\r\n"
"MzNaFw0yMTExMTMxNzA3MzNaMB4xHDAaBgNVBAMMEyouYXp1cmUtZGV2aWNlcy5u\r\n"
"ZXQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCwmkgoceSxc709NWC6\r\n"
"8ttNhqq3vWmQfzwx4emS7JGxiVdeFRBRGgK/EbU18SBtV+jU6uSs7xNU5Xocf2/M\r\n"
"ZwTbGGI4tJD2Rn4MEXR57WUgAaQ6FKI0S2yU8v1BrIpD7860nX0tqKzmbTqwhWwu\r\n"
"gDUTMsZCRKX0YJCC/XYZIQc/9MruoKDfJjfV9040aS6S4ma+5pQZNtr/9KA+UKLN\r\n"
"N4Ix9XxvouGPR+eJF6IAV2SDILwWUleaOIKM2zX7Wea7jAYy3YHRzScUR3R+GEza\r\n"
"y2leozCOJeOjJEOwpI7nUfRzMxnzU/NCryKie6YqFFDjHlnsyV2k4dePDx+431wz\r\n"
"QnrdAgMBAAGjggPUMIID0DCCAQIGCisGAQQB1nkCBAIEgfMEgfAA7gB1AH0+8viP\r\n"
"/4hVaCTCwMqeUol5K8UOeAl/LmqXaJl+IvDXAAABdcKcy60AAAQDAEYwRAIgAinG\r\n"
"OBFQNrQ54ft48BRQ75PWw/fwZ2QTH0LEWHOiHH8CIHeowRxOKeK1G/3xLyVD+c2z\r\n"
"M1PhMTu5irtM08Zm7iaNAHUARJRlLrDuzq/EQAfYqP4owNrmgr7YyzG1P9MzlrW2\r\n"
"gagAAAF1wpzLagAABAMARjBEAiADehjWGgYbXlNCdlByw5+kf7My8jKPuaYCF6KL\r\n"
"Y+AaywIgB575KvjAuIn8m8Y4GvoG65mwL5rar+XQCAVuEl1picYwJwYJKwYBBAGC\r\n"
"NxUKBBowGDAKBggrBgEFBQcDATAKBggrBgEFBQcDAjA+BgkrBgEEAYI3FQcEMTAv\r\n"
"BicrBgEEAYI3FQiH2oZ1g+7ZAYLJhRuBtZ5hhfTrYIFdhYaOQYfCmFACAWQCASUw\r\n"
"gYcGCCsGAQUFBwEBBHsweTBTBggrBgEFBQcwAoZHaHR0cDovL3d3dy5taWNyb3Nv\r\n"
"ZnQuY29tL3BraS9tc2NvcnAvTWljcm9zb2Z0JTIwUlNBJTIwVExTJTIwQ0ElMjAw\r\n"
"Mi5jcnQwIgYIKwYBBQUHMAGGFmh0dHA6Ly9vY3NwLm1zb2NzcC5jb20wHQYDVR0O\r\n"
"BBYEFHkFqnxPVVd3I25rVr6f8B+PIXizMAsGA1UdDwQEAwIEsDBdBgNVHREEVjBU\r\n"
"ghMqLmF6dXJlLWRldmljZXMubmV0ghoqLmFtcXB3cy5henVyZS1kZXZpY2VzLm5l\r\n"
"dIIhKi5zdS5tYW5hZ2VtZW50LWF6dXJlLWRldmljZXMubmV0MIGwBgNVHR8Egagw\r\n"
"gaUwgaKggZ+ggZyGTWh0dHA6Ly9tc2NybC5taWNyb3NvZnQuY29tL3BraS9tc2Nv\r\n"
"cnAvY3JsL01pY3Jvc29mdCUyMFJTQSUyMFRMUyUyMENBJTIwMDIuY3JshktodHRw\r\n"
"Oi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL21zY29ycC9jcmwvTWljcm9zb2Z0JTIw\r\n"
"UlNBJTIwVExTJTIwQ0ElMjAwMi5jcmwwVwYDVR0gBFAwTjBCBgkrBgEEAYI3KgEw\r\n"
"NTAzBggrBgEFBQcCARYnaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraS9tc2Nv\r\n"
"cnAvY3BzMAgGBmeBDAECATAfBgNVHSMEGDAWgBT/L3/hBvQ48y3tJY2Ywv4O9mz8\r\n"
"+jAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDQYJKoZIhvcNAQELBQAD\r\n"
"ggIBAOIkRqCFEdaVYdE3zbDBw3R94dpPQms6w8eJk2epvvqIpb0prU873RKFq0pi\r\n"
"olUjtiDWjZ4i1SVxb4q6Z3bWVQoMT5xZZBXEy4flqyJWe4C+GMlQSjdnBSWEJklc\r\n"
"dHDXdRzo2zhUzphA5766KSLDhX6CwPomeQMc6KZfVTbdCxT939G+l9l9StScqdBl\r\n"
"Ga+yyuw20G/RRAZg1+PFGnG5DOz3HUzCN47z9rQIpj+K3EMgdu7YZbahpcgjL9B3\r\n"
"CKzejOCloyGlmv38lEPj+nJtBVhTuxtjlZvsEP2NPOaoS5qk1P08vxBPrv2x4LTo\r\n"
"f5zBtNiceWqRDVFP5LHbJ4/vGkqA5aEip9tLCVaPLIiAuJUdsRc7WpPQoGQOxXqn\r\n"
"vQVKp7DvBrwgksu5S7L5ZOIykKdYB6fzjSN3NrQ42diD/ibmSYGpIF8IITDiYDTG\r\n"
"aefEE204HaU0ATLiFdgLSqZdxdUAxMv9Ofgif+4Nfg7zeth/NnLSRDx6imafxbl3\r\n"
"gdQGR0VQpEHQ0hdGEx4duG5TtMrL2wYXEJ0pNmbAdtEdanOdAVF+zcm6xInyv+6L\r\n"
"zjONOo8EHKnSATOM1tDCCxvXf76T3YKWG/vEdECMj80w4kid+HLD8KVaLxCsMUmu\r\n"
"Y4Pe5EXP/zxBZ3rgnp4M42MHGq0J9X0Mb9mQxkPYmy4tXRF1\r\n"
"-----END CERTIFICATE-----\r\n"
"-----BEGIN CERTIFICATE-----\r\n"
"MIIFWjCCBEKgAwIBAgIQD6dHIsU9iMgPWJ77H51KOjANBgkqhkiG9w0BAQsFADBa\r\n"
"MQswCQYDVQQGEwJJRTESMBAGA1UEChMJQmFsdGltb3JlMRMwEQYDVQQLEwpDeWJl\r\n"
"clRydXN0MSIwIAYDVQQDExlCYWx0aW1vcmUgQ3liZXJUcnVzdCBSb290MB4XDTIw\r\n"
"MDcyMTIzMDAwMFoXDTI0MTAwODA3MDAwMFowTzELMAkGA1UEBhMCVVMxHjAcBgNV\r\n"
"BAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEgMB4GA1UEAxMXTWljcm9zb2Z0IFJT\r\n"
"QSBUTFMgQ0EgMDIwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQD0wBlZ\r\n"
"qiokfAYhMdHuEvWBapTj9tFKL+NdsS4pFDi8zJVdKQfR+F039CDXtD9YOnqS7o88\r\n"
"+isKcgOeQNTri472mPnn8N3vPCX0bDOEVk+nkZNIBA3zApvGGg/40Thv78kAlxib\r\n"
"MipsKahdbuoHByOB4ZlYotcBhf/ObUf65kCRfXMRQqOKWkZLkilPPn3zkYM5GHxe\r\n"
"I4MNZ1SoKBEoHa2E/uDwBQVxadY4SRZWFxMd7ARyI4Cz1ik4N2Z6ALD3MfjAgEED\r\n"
"woknyw9TGvr4PubAZdqU511zNLBoavar2OAVTl0Tddj+RAhbnX1/zypqk+ifv+d3\r\n"
"CgiDa8Mbvo1u2Q8nuUBrKVUmR6EjkV/dDrIsUaU643v/Wp/uE7xLDdhC5rplK9si\r\n"
"NlYohMTMKLAkjxVeWBWbQj7REickISpc+yowi3yUrO5lCgNAKrCNYw+wAfAvhFkO\r\n"
"eqPm6kP41IHVXVtGNC/UogcdiKUiR/N59IfYB+o2v54GMW+ubSC3BohLFbho/oZZ\r\n"
"5XyulIZK75pwTHmauCIeE5clU9ivpLwPTx9b0Vno9+ApElrFgdY0/YKZ46GfjOC9\r\n"
"ta4G25VJ1WKsMmWLtzyrfgwbYopquZd724fFdpvsxfIvMG5m3VFkThOqzsOttDcU\r\n"
"fyMTqM2pan4txG58uxNJ0MjR03UCEULRU+qMnwIDAQABo4IBJTCCASEwHQYDVR0O\r\n"
"BBYEFP8vf+EG9DjzLe0ljZjC/g72bPz6MB8GA1UdIwQYMBaAFOWdWTCCR1jMrPoI\r\n"
"VDaGezq1BE3wMA4GA1UdDwEB/wQEAwIBhjAdBgNVHSUEFjAUBggrBgEFBQcDAQYI\r\n"
"KwYBBQUHAwIwEgYDVR0TAQH/BAgwBgEB/wIBADA0BggrBgEFBQcBAQQoMCYwJAYI\r\n"
"KwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTA6BgNVHR8EMzAxMC+g\r\n"
"LaArhilodHRwOi8vY3JsMy5kaWdpY2VydC5jb20vT21uaXJvb3QyMDI1LmNybDAq\r\n"
"BgNVHSAEIzAhMAgGBmeBDAECATAIBgZngQwBAgIwCwYJKwYBBAGCNyoBMA0GCSqG\r\n"
"SIb3DQEBCwUAA4IBAQCg2d165dQ1tHS0IN83uOi4S5heLhsx+zXIOwtxnvwCWdOJ\r\n"
"3wFLQaFDcgaMtN79UjMIFVIUedDZBsvalKnx+6l2tM/VH4YAyNPx+u1LFR0joPYp\r\n"
"QYLbNYkedkNuhRmEBesPqj4aDz68ZDI6fJ92sj2q18QvJUJ5Qz728AvtFOat+Ajg\r\n"
"K0PFqPYEAviUKr162NB1XZJxf6uyIjUlnG4UEdHfUqdhl0R84mMtrYINksTzQ2sH\r\n"
"YM8fEhqICtTlcRLr/FErUaPUe9648nziSnA0qKH7rUZqP/Ifmbo+WNZSZG1BbgOh\r\n"
"lk+521W+Ncih3HRbvRBE0LWYT8vWKnfjgZKxwHwJ\r\n"
"-----END CERTIFICATE-----\r\n"
`

**Comment by moizhraj** [comment]
> Have you made sure you only store the root certificate (first in chain) in the `certs.c` and there are **no other certs** in there?

Tried all possible combinations 

- Baltimore Cert from samples
- 1st one from the host
- 2nd one from the host
- 1st and 2nd
- 1st, 2nd, and Baltimore cert from samples
- 2nd and Baltimore cert from samples

yes I did check 

```C
/* Note: for devices with limited resources, only one cert should be loaded. 
   #defines are used to reduce memory footprint of certificates.
   For DE and CN regions, please build with -DUSE_MICROSOFTAZURE_DE_CERT or -DUSE_PORTAL_AZURE_CN_CERT, respectively, 
   if you wish to load ONLY those certs.
*/
```

still no luck

**Comment by maxgerhardt** [comment]
Hm. The ESP32 should be way more powerful and suitable for it than ESP8266 so it makes me wonder what's configured wrongly here. 

>I am using this one

Yes that one's a WROOM-32 with no PSRAM (that would be WROVER).

>1st one from the host

That should have been the right options but it still doesn't work hm.

I suggest you retry it with the pure Arduino IDE version from the [original repo](https://github.com/Azure/azure-iot-arduino) and an ESP32. If the certificate fail comes up again, open an issue there, maybe it's the root of the problem.

**Comment by moizhraj** [comment]
Yea, I have [raised one](https://github.com/Azure/azure-iot-sdk-c/issues/1754) on the main SDK repo, ill try with the Arduino IDE version and see if that works else create one there as well. Thanks, Max, appreciate your help.

**Comment by maxgerhardt** [comment]
They haven't really reacted to your issue. Maybe you should add more information (full log, exact hub name if it's no secret, which I don't think it is). Or they're expecting an issue in https://github.com/Azure/azure-iot-arduino.

**Comment by moizhraj** [comment]
I know :( and there arent many issues open there too for which they are taking time.

I havent really tried with Arduino, got busy with few open PRs so will mostly try next week and see if that works.

**Comment by maxgerhardt** [comment]
Closing as solved since https://github.com/Azure/azure-iot-sdk-c/issues/1754#issuecomment-737042887
